name: imtnan
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+10

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  cached_network_image: ^3.1.0+1
  carousel_slider: ^4.0.0
  connectivity_alert_widget: ^2.0.0+2
  animated_bottom_navigation_bar: ^1.1.0+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dots_indicator: ^2.0.0
  dotted_border: any
  dotted_line: ^3.1.0
  fcm_config: ^3.1.8
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  flutter_holo_date_picker: ^1.0.1+2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_facebook_auth: ^4.4.1+1
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.8.5
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^1.1.0
  geocoding: ^2.0.1
  geolocator: ^9.0.2
  get: ^4.3.8
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.0
  google_sign_in: ^5.3.2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  linktsp_api:
    path: ../linktsp_api_app
  package_info_plus: ^1.3.0
  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.14.0
  pin_code_text_field: ^1.8.0
  pull_to_refresh: ^2.0.0
  share: ^2.0.4
  shimmer: ^2.0.0
  skeletons: ^0.0.3
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  toggle_switch: ^2.0.1
  url_launcher: ^6.0.4
  webview_flutter: ^3.0.2
  sign_in_with_apple: ^4.1.0
  cowpay:
    path: ../cow_payment_sdk
  flutter_guid: ^0.3.1
  facebook_app_events: ^0.17.1
  open_store: ^0.2.4
  firebase_core: ^1.24.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_animate: ^1.0.0
  extended_image: ^6.0.3
  uni_links: ^0.5.1
  dropdown_search: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: Dalton Maag
      fonts:
        - asset: assets/fonts/DaltonMaagCoHeadline.ttf

  assets:
    - assets/images/
    - assets/fonts/
