name: imtnan
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+10

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  badges: ^3.0.2
  cached_network_image: ^3.1.0+1
  carousel_slider: ^4.0.0
  connectivity_alert_widget: ^2.0.0+2
  animated_bottom_navigation_bar: ^1.1.0+1
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  dots_indicator: ^2.0.0
  dotted_border: any
  dotted_line: ^3.1.0
  flutter_switch: ^0.3.2
  fcm_config: ^3.1.8
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  flutter_holo_date_picker: ^1.0.1+2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  flutter_vibrate: ^1.3.0
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.9.1
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^1.1.0
  geocoding: ^2.0.1
  geolocator: ^9.0.2
  get: ^4.3.8
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.0
  google_sign_in: ^5.3.2
  intl: ^0.17.0
  json_annotation: ^4.4.0
  linktsp_api:
    path: ../linktsp_api_app
  package_info_plus: ^3.0.2
  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.14.0
  pin_code_text_field: ^1.8.0
  pull_to_refresh: ^2.0.0
  share: ^2.0.4
  shimmer: ^2.0.0
  skeletons: ^0.0.3
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  toggle_switch: ^2.0.1
  url_launcher: ^6.0.4
  webview_flutter: ^3.0.2
  sign_in_with_apple: ^4.1.0
  flutter_guid: ^0.3.1
  facebook_app_events: ^0.18.3
  open_store: ^0.5.0
  firebase_core: ^2.5.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_animate: ^4.0.0
  extended_image: ^7.0.1
  popover: ^0.2.8
  uni_links: ^0.5.1
  dropdown_search: ^2.0.0 
  fluttertoast: ^8.1.2

  
dev_dependencies:
  build_runner: ^2.1.7
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  fonts:
    - family: Bayshore
      fonts:
        - asset: assets/fonts/Bayshore.ttf
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.otf
          weight: 700
        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 500
        - asset: assets/fonts/Gilroy-Semibold.otf
          weight: 600
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Semibold.ttf
          weight: 600

  assets:
    - assets/images/
    - assets/fonts/
